homeassistant:
  latitude: 31.168
  longitude: 121.432
#  latitude: 31.1689
#  longitude: 121.4325
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  name: Home

zone:
  - name: school
    latitude: 31.278978
    longitude: 121.553436
    icon: mdi:school
    radius: 100

  - name: School（LG）
    longitude: 121.898093
    latitude: 30.90808
    icon: mdi:school
    radius: 250

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

android_ip_webcam:
  - host: 192.168.0.100
    name: ip_webcam

tts:
  - platform: baidu
    app_id: 19508713
    api_key: 6jHIvbdaecOkxqLRNfp2GYqW
    secret_key: NjCiGTinY5NpUZDDmg7H4TmLMhFESPSg
    language: zh
    speed: 5                   #语速0-9（缺省5）
    pitch: 5                     #语调0-9（缺省5）
    volume: 15               #音量0-15（缺省5）
    person: 4                  #声音（0：女，1：男，3：百度合成，4百度合成，缺省0）

media_player:
  - platform: kodi
    host: 127.0.0.1

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#tts:
#  - platform: google_translate
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

