- alias: weather_report
  initial_state: true
  trigger:
  - platform: time_pattern
    hours: 9
    minutes: 37
    seconds: 0
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 0
  action:
  - service: tts.baidu_say
    data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}°C, 湿度{{states('sensor.weather_humidity')}}，风速{{states('sensor.weather_wind_speed')}},
        气压{{states('sensor.weather_pressure')}}
  id: 4b15697b765843bb9278481607d0527d
- id: '1590314135467'
  alias: 新建自动化
  description: ''
  trigger:
  - at: '9:28:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: automation.weather_report
    service: automation.turn_off
