- id: '1590483892499'
  alias: 语音播报
  description: ''
  trigger:
  - at: '8:20:00'
    platform: time
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}°C, 湿度{{states('sensor.weather_humidity')}}，风速{{states('sensor.weather_wind_speed')}},
        气压{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
