
homeassistant:
  latitude: 35.62959
  longitude: 111.394635
  elevation: 0
  unit_system: metric
  time_zone: Asia/Shanghai
  name: Home
  
zone:
  - name: school    
    latitude: 31.278978
    longitude: 121.553436
    icon: mdi:school
    radius: 100

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions: 
      - temperature


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

tts:
  - platform: google_translate
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml