- alias: weather_report
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 16
      minutes: 16
      seconds: 0
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 2
  action:
    - service: tts.baidu_say
      data_template:
       entity_id: media_player.kodi
       message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}°C, 湿度{{states('sensor.weather_humidity')}}，风速{{states('sensor.weather_wind_speed')}}, 气压{{states('sensor.weather_pressure')}}
