- id: '1590135949681'
  alias: weather_report
  description: ''
  trigger:
  - hours: '23'
    minutes: '06'
    platform: time_pattern
    seconds: '0'
  condition:
  - above: '10'
    condition: numeric_state
    entity_id: sensor.weather_temperature
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度，{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
  initial_state: true
- id: '1590333087546'
  alias: new
  description: ''
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
  condition: []
  action:
  - service: kodi.add_to_playlist
