- id: '1590135772643'
  alias: new
  description: ''
  trigger:
  - at: '16:25:00'
    platform: time
  condition: []
  action:
  - service: kodi.call_method

- alias: weather_report
  initial_state: true
  trigger:
  - platform: time_pattern
    hours: 18
    minutes: 50
    seconds: 0
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 10
  action:
  - service: tts.baidu_say
    data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度，{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}