- id: weather
  alias: weather_report
  trigger:
  - at: 07:00:00
    platform: time
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度,百分之{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say
