- id: '1590135787296'
  alias: new
  description: ''
  trigger:
  - at: '16:25:00'
    platform: time
  condition: []
  action:
  - data:
      britness: 150
      rgb_color:
      - 0
      - 255
      - 0
    entity_id: camera.ip_webcam
    service: camera.turn_on
- id: '1590657917784'
  alias: wheather
  description: ''
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度,百分之{{states('sensor.weather_humidity')}}，气压，{{states('sensor.weather_pressure')}}
    service: tts.baidu_say