- id: '1590135782335'
  alias: new
  description: ''
  trigger:
  - at: '16:46:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: camera.ip_webcam
    service: camera.turn_off

- alias: weather_report
  initial_state: true
  trigger: 
  - platform: time_pattern
    hours: 19
    minutes: 53
    seconds: 0  
  condition:
    condition: numeric_state
    entity_id: sensor.weather_temperature
    above: 20
  action:
  - service: tts.baidu_say
    data_template:
      entity_id: media_player.kodi
      message: 现在播报天气信息。温度，{{states('sensor.weather_temperature')}}℃，湿度{{states('sensor.weather_humidity')}}，气压{{states('sensor.weather_pressure')}}
